%global os_release essex

%global enable_doc 0
%global prj client
%global commit_id 0

%if ! (0%{?fedora} > 12 || 0%{?rhel} > 5)
%{!?python_sitelib: %global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}
%endif

Name:             python-novaclient
#Name:             python-novaclient-%{os_release}
Epoch:            1
Version:          2012.1
Release:	  essex
#Release:        0.20120608.1750%{?dist}
Summary:          Python API and CLI for OpenStack Nova

Group:            Applications/System
License:          ASL 2.0
Vendor:           Grid Dynamics Consulting Services, Inc. / USC-ISI
URL:              http://pypi.python.org/pypi/python-novaclient
Source0:          %{name}-%{version}.tar.gz

BuildRoot:        %{_tmppath}/%{name}-%{version}

BuildArch:        noarch
BuildRequires:    python-devel
BuildRequires:    python-setuptools
BuildRequires:    python-nose

Requires:         python-argparse
Requires:         python-httplib2
Requires:         python-prettytable

%description
This is a client for the OpenStack Nova API. There's a Python API (the
novaclient module), and a command-line script (nova). Each implements 100% of
the OpenStack Nova API.

This package contains command-line script.

%if 0%{?enable_doc}
%package doc
Summary:          Documentation for OpenStack Nova API
Group:            Documentation

%description      doc
This is a client for the OpenStack Nova API. There's a Python API (the
novaclient module), and a command-line script (nova). Each implements 100% of
the OpenStack Nova API.

This package contains autogenerated documentation.

%endif

%prep
%setup -q

#patch1 -p1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install -O1 --skip-build --root %{buildroot}

# Delete tests
rm -fr %{buildroot}%{python_sitelib}/tests

%if 0%{?enable_doc}
export PYTHONPATH="$( pwd ):$PYTHONPATH"
sphinx-build -b html docs html

# Fix hidden-file-or-dir warnings
rm -fr .doctrees .buildinfo
%endif

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{python_sitelib}/*

%if 0%{?enable_doc}
%defattr(-,root,root,-)
%files doc
%doc html
%endif

%changelog
* Mon Jun 18 2012 Karandeep Singh <karan AT isi.edu>
- Updated for essex release
* Fri Jan 13 2012 Alessio Ababilov <aababilov@griddynamics.com> - 2011.3
- Merge python-novaclient and openstack-client

* Tue Jul 19 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.5.8-1.20251cc
- 2.5.8 snapshot

* Fri Jul 01 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.5.7-1
- 2.5.7 release

* Tue May 17 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.4.2-1
- 2.4.2 release

* Fri Mar 25 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.4.1-3
- Added python-json in Requires

* Fri Mar 25 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.4.1-2
- Added dependencies on python-httplib2, python-prettytable

* Fri Mar 25 2011 Andrey Brindeyev <abrindeyev@griddynamics.com> - 2.4.1-1
- First build

